import { ApolloProvider } from '@apollo/client';
import type { Metadata } from 'next';
import { ApolloProviderComponent } from '../providers/apolloProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ApolloProviderComponent>{children}</ApolloProviderComponent>
      </body>
    </html>
  );
}
